const state={file:null,audioDuration:0,apiUrl:"http://127.0.0.1:8000",username:"",password:"",connected:false,analyzing:false};
const palette=["#00e5ff","#3c7dff","#9b5cff","#ff2dd1","#ff7a00","#ffe600","#ff3158","#45ffbd"];
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const systemStatus=$("#systemStatus"), statusDot=document.querySelector(".status-dot"), fileInput=$("#fileInput"), dropzone=$("#dropzone"), selectedFile=$("#selectedFile"), fileName=$("#fileName"), fileMeta=$("#fileMeta"), clearFileBtn=$("#clearFileBtn"), waveShell=$("#waveShell"), waveform=$("#waveform"), durationLabel=$("#durationLabel"), waveMarker=$("#waveMarker"), analyzeBtn=$("#analyzeBtn"), analyzeLabel=$("#analyzeLabel"), resetBtn=$("#resetBtn"), processPanel=$("#processPanel"), pipelineProgress=$("#pipelineProgress"), resultsPanel=$("#results"), timelinePanel=$("#timelinePanel"), resultStack=$("#resultStack"), resultsCount=$("#resultsCount"), accessPanel=$("#accessPanel"), accessForm=$("#accessForm"), accessStatus=$("#accessStatus"), apiUrlInput=$("#apiUrl"), apiUserInput=$("#apiUser"), apiPassInput=$("#apiPass"), dropTitle=$("#dropTitle"), dropSub=$("#dropSub"), openAccessBtn=$("#openAccessBtn");
function motionAnimate(target,keyframes,options={}){return window.Motion?.animate?window.Motion.animate(target,keyframes,options):null}
function setSystemState(mode,text){systemStatus.textContent=text;statusDot.style.background=mode==="online"?"var(--green)":mode==="busy"?"var(--cyan)":"var(--red)";statusDot.style.boxShadow=mode==="online"?"0 0 13px rgba(69,255,189,.7)":mode==="busy"?"0 0 13px rgba(0,229,255,.7)":"0 0 13px rgba(255,49,88,.7)"}
function basicAuthHeader(){return"Basic "+btoa(unescape(encodeURIComponent(state.username+":"+state.password)))}
function formatBytes(bytes){if(!bytes)return"0 B";const units=["B","KB","MB","GB"];const i=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),3);return(bytes/Math.pow(1024,i)).toFixed(i?1:0)+" "+units[i]}
function formatTime(seconds){const s=Math.max(0,Math.floor(Number(seconds)||0)),min=Math.floor(s/60),sec=s%60;return String(min).padStart(2,"0")+":"+String(sec).padStart(2,"0")}
function parseTimestamp(timestamp){const m=String(timestamp||"").match(/(\d+):(\d+)\s*-\s*(\d+):(\d+)/);return m?{start:+m[1]*60 + +m[2],end:+m[3]*60 + +m[4]}:null}
function normalizeConfidence(item){const raw=Number(item?.confidence);if(Number.isFinite(raw))return{raw,pct:Math.max(0,Math.min(100,raw*100))};const pct=Number(String(item?.confidence_percentage||"").replace("%",""));return Number.isFinite(pct)?{raw:pct/100,pct:Math.max(0,Math.min(100,pct))}:{raw:0,pct:0}}
function getInstrument(item){return item?.instrument||item?.original_prediction||"Unknown instrument"}
function resetPipeline(){$$(".process-step").forEach(s=>{s.classList.remove("active","done");s.querySelector(".step-state").textContent="WAITING"});pipelineProgress.style.width="0%"}
function updatePipeline(i,status){const step=document.querySelector('.process-step[data-step="'+i+'"]');if(!step)return;step.classList.toggle("active",status==="active");step.classList.toggle("done",status==="done");step.querySelector(".step-state").textContent=status==="done"?"DONE":"RUNNING"}
function drawWaveform(samples=null){const ctx=waveform.getContext("2d"),dpr=devicePixelRatio||1,w=waveform.clientWidth||760,h=110;waveform.width=Math.round(w*dpr);waveform.height=Math.round(h*dpr);ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);ctx.strokeStyle="rgba(0,229,255,.10)";ctx.lineWidth=1;for(let y=15;y<h;y+=20){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}const points=samples||Array.from({length:Math.max(90,Math.floor(w/5))},(_,i)=>.08+(Math.abs(Math.sin(i*.19))*.65+Math.abs(Math.cos(i*.055))*.35)*(.15+(i%17)/70));const bw=Math.max(1.5,w/points.length*.72),gap=w/points.length,g=ctx.createLinearGradient(0,0,w,0);g.addColorStop(0,"#00e5ff");g.addColorStop(.45,"#3c7dff");g.addColorStop(.72,"#9b5cff");g.addColorStop(1,"#ff2dd1");ctx.fillStyle=g;points.forEach((a,i)=>{const x=i*gap,hh=Math.max(2,a*(h-20));ctx.fillRect(x,h/2-hh/2,bw,hh)})}
async function createAudioWaveform(file){const C=window.AudioContext||window.webkitAudioContext;if(!C){drawWaveform();return}try{const ctx=new C(),buf=await ctx.decodeAudioData((await file.arrayBuffer()).slice(0)),data=buf.getChannelData(0);state.audioDuration=buf.duration;durationLabel.textContent=formatTime(state.audioDuration);const n=Math.max(120,Math.min(420,Math.floor((waveform.clientWidth||760)/2.2))),size=Math.max(1,Math.floor(data.length/n)),samples=[];for(let i=0;i<n;i++){let max=0;const start=i*size,end=Math.min(data.length,start+size);for(let j=start;j<end;j+=Math.max(1,Math.floor(size/20)))max=Math.max(max,Math.abs(data[j]));samples.push(Math.min(1,max))}drawWaveform(samples);await ctx.close()}catch{drawWaveform()}}
function setAccessMessage(m,type=""){accessStatus.className="access-status "+type;accessStatus.textContent=m}
function openAccess(show=true){if(show){accessPanel.classList.remove("hidden");motionAnimate(accessPanel,{opacity:[0,1],y:[-12,0]},{duration:.35,easing:"ease-out"})}else accessPanel.classList.add("hidden")}
function handleFile(file){if(!file||!file.type.startsWith("audio/")){setAccessMessage("Please select a valid audio file.","error");return}state.file=file;selectedFile.classList.remove("hidden");waveShell.classList.remove("hidden");fileName.textContent=file.name;fileMeta.textContent=formatBytes(file.size)+" · "+(file.type||"audio");dropTitle.textContent="SIGNAL LOADED";dropSub.textContent="Ready for backend inference";analyzeBtn.disabled=false;motionAnimate(selectedFile,{opacity:[0,1],y:[12,0]},{duration:.4,easing:"ease-out"});motionAnimate(waveShell,{opacity:[0,1],y:[8,0]},{duration:.45,delay:.08,easing:"ease-out"});createAudioWaveform(file)}
function clearFile(){state.file=null;state.audioDuration=0;fileInput.value="";selectedFile.classList.add("hidden");waveShell.classList.add("hidden");dropTitle.textContent="DROP AUDIO HERE";dropSub.textContent="or click to browse your machine";analyzeBtn.disabled=true;durationLabel.textContent="00:00";waveMarker.style.display="none";drawWaveform()}
async function connectAPI(){state.apiUrl=apiUrlInput.value.trim().replace(/\/$/,"");state.username=apiUserInput.value;state.password=apiPassInput.value;setAccessMessage("Testing / ...");setSystemState("busy","TESTING API");try{const r=await fetch(state.apiUrl+"/",{headers:{Authorization:basicAuthHeader()}});if(!r.ok)throw new Error("HTTP "+r.status);state.connected=true;setAccessMessage("Connection established. FastAPI is responding.","success");setSystemState("online","API ONLINE");openAccess(false)}catch(e){state.connected=false;setAccessMessage("Connection failed: "+e.message,"error");setSystemState("offline","API DISCONNECTED")}}
async function runAnalysis(){if(!state.file){setAccessMessage("Select an audio file first.","error");return}if(!state.connected){openAccess(true);setAccessMessage("Connect to the FastAPI backend before analyzing.","error");return}if(state.analyzing)return;state.analyzing=true;analyzeBtn.disabled=true;analyzeLabel.textContent="ANALYZING";processPanel.classList.remove("hidden");timelinePanel.classList.add("hidden");resetPipeline();resultStack.innerHTML='<div class="empty-state"><span class="empty-orbit"></span><strong>RUNNING INFERENCE</strong><span>Waiting for FastAPI + CLAP results...</span></div>';setSystemState("busy","INFERENCE RUNNING");motionAnimate(processPanel,{opacity:[0,1],y:[8,0],height:[0,"auto"]},{duration:.4,easing:"ease-out"});const body=new FormData();body.append("file",state.file);try{const rp=fetch(state.apiUrl+"/detect",{method:"POST",headers:{Authorization:basicAuthHeader()},body});for(let i=0;i<5;i++){updatePipeline(i,"active");pipelineProgress.style.width=((i+1)/5)*84+"%";await new Promise(r=>setTimeout(r,340));updatePipeline(i,"done")}const r=await rp;if(!r.ok){let d="HTTP "+r.status;try{const j=await r.json();if(j?.detail)d=j.detail}catch{}throw new Error(d)}const payload=await r.json();pipelineProgress.style.width="100%";renderResults(payload);setSystemState("online","API ONLINE");openAccess(false)}catch(e){setSystemState("offline","API ERROR");resultStack.innerHTML='<div class="empty-state"><strong>INFERENCE FAILED</strong><span>'+escapeHtml(e.message)+'</span></div>'}finally{state.analyzing=false;analyzeBtn.disabled=!state.file;analyzeLabel.textContent="ANALYZE AGAIN"}}
function renderResults(payload){const results=Array.isArray(payload?.instruments)?payload.instruments:[];resultsCount.textContent=results.length+" DETECTED";$("#metricInstruments").textContent=results.length||"0";if(!results.length){$("#metricTop").textContent="—";$("#metricScore").textContent="—";resultStack.innerHTML='<div class="empty-state"><strong>NO MATCHES ABOVE THRESHOLD</strong><span>The backend returned no instrument candidates after dynamic filtering.</span></div>';timelinePanel.classList.add("hidden");return}const scores=results.map(normalizeConfidence),best=scores.reduce((b,x,i)=>x.pct>scores[b].pct?i:b,0),top=results[best];$("#metricTop").textContent=getInstrument(top);$("#metricScore").textContent=scores[best].raw.toFixed(3);resultStack.innerHTML="";results.forEach((item,i)=>{const score=normalizeConfidence(item),name=getInstrument(item),accent=palette[i%palette.length],card=document.createElement("div");card.className="result-card";card.style.setProperty("--accent",accent);card.innerHTML='<div class="result-main"><div class="result-top"><span class="result-name">'+escapeHtml(name)+'</span><span class="result-tag">MATCH #'+String(i+1).padStart(2,"0")+'</span></div><div class="score-line"><div class="score-track"><div class="score-fill"></div></div><span class="score-num">'+score.pct.toFixed(2)+'%</span></div><div class="result-sub"><span>raw '+score.raw.toFixed(4)+'</span><span>cosine similarity</span></div></div><div class="result-side"><span class="timestamp">'+escapeHtml(item.timestamp||"Peak window unavailable")+'</span></div>';resultStack.appendChild(card);motionAnimate(card,{opacity:[0,1],x:[-18,0],scale:[.985,1]},{duration:.42,delay:i*.055,easing:"ease-out"});motionAnimate(card.querySelector(".score-fill"),{width:["0%",score.pct+"%"]},{duration:.75,delay:.18+i*.055,easing:"ease-out"})});renderTimeline(results)}
function renderTimeline(results){const duration=Math.max(state.audioDuration||0,10),rows=[];results.forEach((item,i)=>{const p=parseTimestamp(item.timestamp);if(!p)return;const score=normalizeConfidence(item),name=getInstrument(item),accent=palette[i%palette.length],left=Math.max(0,Math.min(98,p.start/duration*100)),width=Math.max(4,Math.min(100-left,(p.end-p.start)/duration*100));rows.push('<div class="timeline-row"><div class="timeline-label">'+escapeHtml(name)+'</div><div><div class="timeline-track"><span class="timeline-hit" style="left:'+left+'%;width:'+width+'%;--accent:'+accent+'"></span></div>'+(i===0?'<div class="timeline-scale"><span>00:00</span><span>'+escapeHtml(formatTime(duration/2))+'</span><span>'+escapeHtml(formatTime(duration))+'</span></div>':"")+'</div></div>')});if(!rows.length){timelinePanel.classList.add("hidden");return}timelinePanel.classList.remove("hidden");$("#timeline").innerHTML=rows.join("");motionAnimate(timelinePanel,{opacity:[0,1],y:[10,0]},{duration:.45,easing:"ease-out"})}
function escapeHtml(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function resetConsole(){state.analyzing=false;resetPipeline();clearFile();processPanel.classList.add("hidden");timelinePanel.classList.add("hidden");resultsCount.textContent="0 DETECTED";$("#metricInstruments").textContent="—";$("#metricTop").textContent="—";$("#metricScore").textContent="—";resultStack.innerHTML='<div class="empty-state"><span class="empty-orbit"></span><strong>NO ANALYSIS YET</strong><span>Upload audio and run the classifier to populate the matrix.</span></div>';analyzeLabel.textContent="ANALYZE AUDIO";setSystemState(state.connected?"online":"offline",state.connected?"API ONLINE":"API DISCONNECTED")}
fileInput.addEventListener("change",e=>handleFile(e.target.files?.[0]));["dragenter","dragover"].forEach(n=>dropzone.addEventListener(n,e=>{e.preventDefault();dropzone.classList.add("dragging")}));["dragleave","drop"].forEach(n=>dropzone.addEventListener(n,e=>{e.preventDefault();dropzone.classList.remove("dragging")}));dropzone.addEventListener("drop",e=>handleFile(e.dataTransfer.files?.[0]));clearFileBtn.addEventListener("click",clearFile);analyzeBtn.addEventListener("click",runAnalysis);resetBtn.addEventListener("click",resetConsole);openAccessBtn.addEventListener("click",()=>openAccess(true));$("#closeAccessBtn").addEventListener("click",()=>openAccess(false));accessForm.addEventListener("submit",e=>{e.preventDefault();connectAPI()});$$(".rail-btn").forEach(b=>b.addEventListener("click",()=>{$$(".rail-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.target)?.scrollIntoView({behavior:"smooth",block:"start"})}));window.addEventListener("resize",()=>{if(!waveShell.classList.contains("hidden"))drawWaveform()});
motionAnimate(".eyebrow",{opacity:[0,1],y:[14,0]},{duration:.5,easing:"ease-out"});motionAnimate("h1",{opacity:[0,1],y:[22,0]},{duration:.65,delay:.08,easing:"ease-out"});motionAnimate(".hero-copy",{opacity:[0,1],y:[16,0]},{duration:.55,delay:.16,easing:"ease-out"});motionAnimate(".panel",{opacity:[0,1],y:[18,0],scale:[.985,1]},{duration:.55,delay:.12,easing:"ease-out"});drawWaveform();